targets:
  $default:
    builders:
      json_serializable:
        options:
          generic_argument_factories: true
          include_if_null: false
          field_rename: none
          explicit_to_json: true
      freezed:
        options:
          union_key: type
          union_value_case: pascal
