name: domain
description: "A new Flutter package project."

version: 0.0.2+25.04.24.02

publish_to: "none"

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: 4.8.1
  shared:
    path: ../shared
  dartz: null
  jwt_decoder: ^2.0.1
  get_it: ^7.6.8

dev_dependencies:
  build_runner: null
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: null
  json_serializable: 6.7.1


flutter: null
