targets:
  $default:
    builders:
      json_serializable:
        options:
          generic_argument_factories: true
          include_if_null: false
          field_rename: snake
          explicit_to_json: true
