name: shared
description: "A new Flutter package project."
version: 0.0.1
publish_to: "none"

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  android_id: 0.3.6
  asn1lib: 1.5.2
  async: 2.11.0
  dartx: 1.2.0
  decimal: 2.3.3
  device_info_plus: 9.1.2
  encrypt: 5.0.3
  flutter:
    sdk: flutter
  flutter_udid: 3.0.0
  freezed: ^2.5.2
  flutter_contacts: ^1.1.8
  freezed_annotation: ^2.4.1
  get_it: 7.6.8
  injectable: 2.4.1
  intl: 0.18.1
  json_annotation: 4.8.1
  package_info_plus: ^8.0.0
  rxdart: 0.27.7
  apple_product_name: 2.4.0
  path_provider: ^2.1.3
  http: ^1.2.1
  basic_utils: ^5.7.0
  dartz: ^0.10.1
  flutter_logs: ^2.1.12

dev_dependencies:
  build_runner: ^2.4.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  json_serializable: 6.7.1
  envied_generator: ^0.5.4+1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware
# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
